const kpis = [
  {
    id: 1,
    name: 'Sales',
    description: 'Monthly sales for the last 6 months',
    type: 'KPI',
    labels: 'sales',
    isFavorite: true,
    createdAt: new Date(),
    updatedAt: new Date(),
    targetValue: 50000,
    currentValue: 48000,
    targetDate: new Date('2024-12-31'),
    currentDate: new Date('2024-09-30'),
  },
  {
    id: 2,
    name: 'Profit Margin',
    description: 'Current profit margin as a percentage',
    type: 'KPI',
    labels: 'profit_margin',
    createdAt: new Date(),
    updatedAt: new Date(),
    targetValue: 20,
    currentValue: 18,
    targetDate: new Date('2024-12-31'),
    currentDate: new Date('2024-09-30'),
  },
  {
    id: 3,
    name: 'Expenses',
    description: 'Annual expenses for the company',
    type: 'KPI',
    labels: 'expenses',
    createdAt: new Date(),
    updatedAt: new Date(),
    targetValue: 100000,
    currentValue: 80000,
    targetDate: new Date('2024-12-31'),
    currentDate: new Date('2024-09-30'),
  },
  {
    id: 4,
    name: 'Revenue',
    description: 'Annual revenue for the company',
    type: 'KPI',
    labels: 'revenue',
    createdAt: new Date(),
    updatedAt: new Date(),
    targetValue: 2000000,
    currentValue: 1800000,
    targetDate: new Date('2024-12-31'),
    currentDate: new Date('2024-09-30'),
  },
];

const layouts = [
  {
    id: 5,
    name: 'Sales Dashboard',
    description: 'A dashboard for displaying sales data',
    type: 'LAYOUT',
    labels: 'sales',
    createdAt: new Date(),
    updatedAt: new Date(),
    kpis: '[1,2]',
  },
  {
    id: 6,
    name: 'Expenses Dashboard',
    description: 'A dashboard for displaying expenses data',
    type: 'LAYOUT',
    labels: 'expenses',
    createdAt: new Date(),
    updatedAt: new Date(),
    isFavorite: true,
    kpis: '[3]',
  },
  {
    id: 7,
    name: 'Profit Margin Dashboard',
    description: 'A dashboard for displaying profit margin data',
    type: 'LAYOUT',
    labels: 'profit_margin',
    createdAt: new Date(),
    updatedAt: new Date(),
    kpis: '[2]',
  },
];

const storyboards = [
  {
    id: 8,
    name: 'Sales Storyboard',
    description: 'A storyboard for displaying sales data',
    type: 'STORYBOARD',
    labels: 'sales',
    createdAt: new Date(),
    updatedAt: new Date(),
    layoutId: 1,
    insights: "['Sales trends over time', 'Top 5 sales performers']",
  },
  {
    id: 9,
    name: 'Expenses Storyboard',
    description: 'A storyboard for displaying expenses data',
    type: 'STORYBOARD',
    labels: 'expenses',
    createdAt: new Date(),
    updatedAt: new Date(),
    layoutId: 2,
    insights: "['Expenses trends over time', 'Top 5 expenses contributors']",
  },
  {
    id: 10,
    name: 'Profit Margin Storyboard',
    description: 'A storyboard for displaying profit margin data',
    type: 'STORYBOARD',
    labels: 'profit_margin',
    isFavorite: true,
    createdAt: new Date(),
    updatedAt: new Date(),
    layoutId: 3,
    insights: "['Profit margin trends over time', 'Top 5 profit margin leaders']",
  },
];

const data = [...kpis, ...layouts, ...storyboards];

export default data;

